const DELETE_TASK = 'DELETE_TASK';
const ADD_TASK = 'ADD_TASK';
const FORM_CHANGE_TASK_NAME = 'FORM_CHANGE_TASK_NAME';
const FORM_CHANGE_TASK_AUTHOR = 'FORM_CHANGE_TASK_AUTHOR';
const FORM_SUBMIT = 'FORM_SUBMIT';

export {
  DELETE_TASK,
  ADD_TASK,
  FORM_CHANGE_TASK_NAME,
  FORM_CHANGE_TASK_AUTHOR,
  FORM_SUBMIT,
};
