apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp
        image: [replace-with-account-id].dkr.ecr.[region].amazonaws.com/[repository-name]:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: myapp
